name: "Build PDF"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/moderncv/debian-texlive-docker:main
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build PDF
        run: latexmk ./cv.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: cv.pdf
          path: ./cv.pdf
