name: LaTeX Taji PDF
'on':
  push:
    branches:
      - master
  workflow_dispatch: null

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Build
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex
      - name: Copy
        run: |
          mkdir out
          cp ./cv.pdf ./out/cv.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: taji-cv
          path: ./out/cv.pdf

release:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Download CV
      uses: actions/download-artifact@v4
      with:
        name: taji-cv
    - name: Verify Artifact
      run: ls -al
    - name: Create Release
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      run: >
        mkdir -p out

        mv cv.pdf out/cv.pdf

        gh release create latest out/cv.pdf --title "Latest CV" --notes
        "Automatically generated CV."
