name: LaTeX Taji CV

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Build CV Artifact
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex

      - name: Copy CV Artifact
        run: |
          mkdir -p out
          cp ./cv.pdf ./out/cv.pdf

      - name: Upload CV Artifact
        uses: actions/upload-artifact@v4
        with:
          name: taji-cv
          path: ./out/cv.pdf

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Download CV Artifact
        uses: actions/download-artifact@v4
        with:
          name: taji-cv

      - name: Verify Artifact
        run: ls -al

      - name: Determine Unique Tag
        id: set_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_BASE="cv-$(date +'%Y')"
          COUNT=0
          UNIQUE_TAG="$TAG_BASE"
          while gh release view "$UNIQUE_TAG" &>/dev/null; do
            COUNT=$((COUNT + 1))
            UNIQUE_TAG="${TAG_BASE}-v${COUNT}"
          done
          echo "TAG=$UNIQUE_TAG" >> $GITHUB_ENV
          echo "Unique tag determined: $UNIQUE_TAG"

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ env.TAG }}
        run: |
          mkdir -p out
          mv cv.pdf out/cv.pdf
          TITLE="Latest CV | $(date +'%b %d, %Y')"
          echo "Creating release with tag: $TAG"
          gh release create "$TAG" out/cv.pdf --title "$TITLE" --notes "Automatically generated CV by GitHub Actions" --latest
